Add option to disable creeper exploding blocks
Nukkit-coders/MobPlugin pull request #240
Opened 2021-07-26 17:29 UTC by PleaseInsertNameHere

This pull request adds an option to disable creeper exploding blocks (#199)

2021-07-26 23:59 UTC, PetteriM1 requested changes

2021-07-26 23:59 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +            if (ev.isBlockBreaking() && this.level.getGameRules().getBoolean(GameRule.MOB_GRIEFING) && MobPlugin.getInstance().config.pluginConfig.getBoolean("creeper-explode-blocks")) {
Please do not use pluginConfig here

2021-07-26 23:59 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/Config.java
> +                pluginConfig.set("creeper-explode-blocks", true);
Due to how the config updating is currently handled you should add this to every old config version we can update

2021-07-26 23:59 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +            if (ev.isBlockBreaking() && this.level.getGameRules().getBoolean(GameRule.MOB_GRIEFING) && MobPlugin.getInstance().config.pluginConfig.getBoolean("creeper-explode-blocks")) {
I think using ev.setBlockBreaking(false) would be a better solution

2021-07-27 06:07 UTC, PleaseInsertNameHere commented on src/main/java/nukkitcoders/mobplugin/Config.java
> +                pluginConfig.set("creeper-explode-blocks", true);
Sorry, what do I have to change here?

2021-07-27 13:53 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/Config.java
> +                pluginConfig.set("creeper-explode-blocks", true);
`pluginConfig.set("creeper-explode-blocks", true);` for all old config versions, not just 15

2021-07-27 13:53 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +            if (ev.isBlockBreaking() && this.level.getGameRules().getBoolean(GameRule.MOB_GRIEFING) && MobPlugin.getInstance().config.pluginConfig.getBoolean("creeper-explode-blocks")) {
And do not use pluginConfig here

2021-07-27 14:45 UTC, PetteriM1 requested changes

2021-07-27 14:45 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +                ev.setBlockBreaking(false);
This should be done before the event is called on line 84

2021-07-27 14:53 UTC, PleaseInsertNameHere commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +                ev.setBlockBreaking(false);
Oops, didn't see. Give me a second.

2021-07-27 15:05 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +                ev.setBlockBreaking(false);
You still do it after `callEvent`

2021-07-27 15:18 UTC, PleaseInsertNameHere commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +                ev.setBlockBreaking(false);
Oops, sorry. Fixed it.

2021-07-27 15:26 UTC, PetteriM1 commented on src/main/java/nukkitcoders/mobplugin/entities/monster/walking/Creeper.java
> +        if (MobPlugin.getInstance().config.creeperExplodeBlocks) {
Either you forgot the `!` or the boolean should be called creepers DON'T explode blocks

2021-07-27 15:26 UTC, PetteriM1 commented on src/main/resources/config.yml
> +  # disable creeper explode blocks
Disable?

2021-07-27 15:31 UTC, PleaseInsertNameHere commented
Alright, changed it. Should be better now.

2021-07-27 15:55 UTC, merged